name = "cloudflare-b2"
main = "index.js"
compatibility_date = "2024-04-05"

routes = [
  { pattern = "img99.9truyen.online", custom_domain = true }
]

[vars]
# Backblaze B2 Key ID
B2_APPLICATION_KEY_ID = "0042deabeb7926c0000000001"

# Endpoint chuẩn theo bucket của Bro
B2_ENDPOINT = "s3.us-west-004.backblazeb2.com"

# Chỉ dùng một bucket cố định
BUCKET_NAME = "IMG1423"

# Không cho list bucket (private bucket)
ALLOW_LIST_BUCKET = "false"

# Không dùng rclone
RCLONE_DOWNLOAD = "false"
